name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Coverage
    steps:
    - name: Checkout
      run: |
        git clone
        cd
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install -D
    - name: Run tests
      run: npm run coveralls

    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

